
default: help
.PHONY: default

help:
	@echo 'Usage:'
	@echo '	$$ make [action]'
	@echo
	@echo 'Ex:'
	@echo '	$$ make'
	@echo '	$$ make help'
	@echo
	@echo '	$$ make prepare'
	@echo
	@echo '	$$ make build'
	@echo
	@echo '	$$ make clean'
	@echo
.PHONY: help


prepare:
	@./prepare.sh
.PHONY: prepare


build:
	@./build.sh
.PHONY: build


clean:
	@./clean.sh
.PHONY: clean
